First design
Tekkon/robot_factory pull request #1
Opened 2019-08-19 12:31 UTC by Tekkon

2019-08-19 23:50 UTC, aya-soft requested changes

2019-08-19 23:50 UTC, aya-soft commented on robot.rb
> +  def forget
Зачем за непонятным методом скрывать простое: `robo.name = nil`?

2019-08-19 23:50 UTC, aya-soft commented on robot_factory.rb
>    include NameGenerator
Подмешивание модуля - это форма наследования, создающего жесткую зависимость! Мы вроде говорили, что изменение алгоритма построения имени высоко вероятное событие. Такой реализацией мы себя сильно ограничиваем.

2019-08-19 23:50 UTC, aya-soft commented on robot_factory.rb
> +    @robots = []
Зачем хранить объекты роботов, которые только память жрут, если можно просто имена?

2019-08-19 23:50 UTC, aya-soft commented on robot_factory.rb
> +  def create_robot
Отличное название

2019-08-19 23:50 UTC, aya-soft commented on robot_factory.rb
> +    robots << Robot.new(generate_unique_name)
Сгенерировали имя, добавили его в массив имен, и вернули нового робота с этим именем.

2019-08-19 23:50 UTC, aya-soft commented on robot_factory.rb
> +    loop do
зачем так громоздко?

2019-08-20 04:46 UTC, Tekkon commented on robot_factory.rb
>    include NameGenerator
Алгоритм изменения имени -  в модуле. Если алгоритм меняется, изменяем модуль, а не класс RobotFactory. Или создаем другой модуль с другим алгоритмом и добавляем в RobotFactory вместо NameGenerator

2019-08-20 04:47 UTC, Tekkon commented on robot_factory.rb
> +    @robots = []
Если кроме имен появятся еще какие-то параметры, то не нужно будет создавать еще какие-то массивы. У нас есть массив роботов, из которого можно достать любую информацию об этих роботах.

2019-08-20 04:47 UTC, Tekkon commented on robot_factory.rb
> +    loop do
Не понял, что тут громоздкого?

2019-08-22 21:33 UTC, aya-soft requested changes

2019-08-22 21:33 UTC, aya-soft commented on app.rb
> +    @robot_factory = RobotFactory.build
Ну тут build можно было не делать :) у нас же всего один вызов. Если у нас есть какой-нибудь пример, это не значит, что его нужно везде повторять ;)

2019-08-22 21:33 UTC, aya-soft commented on app/robot_factory.rb
> +
Вот тут очень многословно:
```
  def generate_unique_name
    loop do
      name = name_generator.generate_name
      return name if is_unique?(name)
    end
  end
  def is_unique?(name)
    !names.include?(name)
  end
```

1) is_unique? кажется не нужен, мы его вроде не будем нигде больше использовать
2) generate_unique_name можно переписать так:
```
  def new_robo_name
    name = name_generator.generate_name while names.include?(name)
    name
  end
```
обрати внимание, как я изменил название, лучше чтобы название метода отвечало на вопрос ЧТО я даю, чем КАК я это делаю. Все правила можно внутри метода посмотреть. Хотя `new_uniq_robo_name` тоже можно.

2019-08-26 17:26 UTC, aya-soft requested changes

2019-08-26 17:26 UTC, aya-soft commented on app/robot.rb
> +  def reset_settings
Я не думаю, что оставлять робота без имени совсем - хорошая идея, давай уберем этот метод вообще,
а вместо него добавим `RobotFatory.reset_robot(robot)` и там уже поменяем имя робота

2019-08-26 17:26 UTC, aya-soft commented on app/robot.rb
> +  def initialize(name = nil)
Дефолтное значение nil - плохо! НЕ должно быть без имени роботов, мы это правда жестко не проверяем, но хотя бы не провоцировать

2019-08-26 17:26 UTC, aya-soft commented on app/robot_factory.rb
> +  def new_robot_unique_name
этот метод нужно спрятать за `private`, кроме фабрики никто не должен иметь доступ к нашему алгоритму

2019-08-26 17:26 UTC, aya-soft commented on app/robot_factory.rb
> +    Robot.new
`Robot.new(new_robot_unique_name)` при создании сразу даем уникальное имя, иначе зачем нам фабрика вообще. Она не просто роботов создает, но создает их по правилам

2019-08-26 17:26 UTC, aya-soft commented on app/robot_factory.rb
> +  def new_robot_unique_name
В имени определения стоят впереди, лучше  `new_uniq_robot_name`

2019-08-26 17:26 UTC, aya-soft commented on spec/name_generator_spec.rb
> +      assert /[A-Z][A-Z]\d\d\d/ === name_generator.generate_name
тут ты проверил всего лишь, что единичный вызов метода возвращает шаблонную строку, но если я перепишу реализацию метода так, то тест пройдет, а решение будет неправильным:
```
def generate_name
  "AB123"
end
```

2019-08-26 17:26 UTC, aya-soft commented on spec/robot_factory_spec.rb
> +      assert_equal robot_factory.robot_names, []
Не надо проверять заполненность внутренних атрибутов, мы тестируем работу класса при правильном использовании

2019-08-26 17:26 UTC, aya-soft commented on spec/robot_factory_spec.rb
> +      assert !robot_factory.name_generator.nil?
тоже самое

2019-08-26 17:26 UTC, aya-soft commented on spec/robot_factory_spec.rb
> +      assert_kind_of Robot, robot_factory.create_robot
Тут лучше проверять не тип возвращаемого объекта, а то, что вернулся с правильными атрибутами

2019-08-26 17:26 UTC, aya-soft commented on spec/robot_factory_spec.rb
> +      assert !robot_factory.robot_names.take(robot_factory.robot_names.length - 1).include?(robot_factory.send(:new_robot_unique_name))
Сомнительная проверка на уникальность, проверяет только то, что возвращаемое значение не то, что в массиве, не более

2019-08-26 17:26 UTC, aya-soft commented on spec/robot_factory_spec.rb
> +      assert_send [robot_factory.name_generator, :generate_name]
Зачем это проверять?

2019-09-04 04:51 UTC, merged